version: 1
formatters:
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: standard
    filename: logs/app.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
loggers:
  '':  # Root logger
    handlers: [console, file]
    level: DEBUG
    propagate: true
  data_collection:
    level: DEBUG
    handlers: [console, file]
    propagate: false
  prediction:
    level: DEBUG
    handlers: [console, file]
    propagate: false
  drift_detection:
    level: DEBUG
    handlers: [console, file]
    propagate: false
